### ISSUE TITLE
Can't install requirements with python 3.9

### ISSUE THREAD

**Issue by brabiega** [ovh/fiowebviewer#2]
```tables``` package is pined in requirements.txt file.

The specified version doesn't seem to work with Python 3.9

```
   /usr/include/python3.9/cpython/code.h:120:38: note: expected ‘PyObject *’ {aka ‘struct _object *’} but argument is of type ‘int’
      120 |         PyObject *, PyObject *, int, PyObject *);
          |                                      ^~~~~~~~~~
    tables/utilsextension.c:331:11: error: too many arguments to function ‘PyCode_New’
      331 |           PyCode_New(a, 0, k, l, s, f, code, c, n, v, fv, cell, fn, name, fline, lnos)
          |           ^~~~~~~~~~
    tables/utilsextension.c:24479:15: note: in expansion of macro ‘__Pyx_PyCode_New’
    24479 |     py_code = __Pyx_PyCode_New(
          |               ^~~~~~~~~~~~~~~~
    In file included from /usr/include/python3.9/code.h:13,
                     from /usr/include/python3.9/Python.h:117,
                     from tables/utilsextension.c:17:
    /usr/include/python3.9/cpython/code.h:117:28: note: declared here
      117 | PyAPI_FUNC(PyCodeObject *) PyCode_New(
          |                            ^~~~~~~~~~
    error: command '/usr/bin/gcc' failed with exit code 1
```
